name="Silas Sakwa"
print(name.upper())
print(name.capitalize())
print(name.strip())
print(3+3)
print("the sum of 3+3 is",3+3)
print("the difference of 31-10 is",31-10)
print(3*4)
print(12%5)
print(2**4)
print(30/5)
print(30//5)
print("enter weight in metre squares")
wei=float(input("weka weight"))
print("enter height in metre squares")
hei=float(input("weka height"))
BMI=hei/wei
print("BMI is:",BMI)
print(25*150)